baseURL = "/"
languageCode = "en-us"
title = "OSLC - Open Services for Lifecycle Collaboration"
theme = "oslc"
layoutDir = "partials"
disableLiveReload = false
watch = true
uglyURL = true
paginate = 15

disqusShortname = "yourdiscussshortname"
disqus_identifier = ""
disqus_title = ""
disqus_url = ""

[taxonomies]
    tag = "tags"
    category = "categories"

# Main menu

[[menu.main]]
    name = "Why?"
    identifier = "why"
    url = "/why"
    weight = 1

[[menu.main]]
    name = "About"
    identifier = "about"
    url  = "/about/mission"
    weight = 2

[[menu.main]]
    name = "Resources"
    url  = "/resources/"
    weight = 3

[[menu.main]]
    name = "Contribute"
    url  = "/contribute/"
    weight = 4

[[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/OSLC"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/oslcNews"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:webmaster@open-services.net"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

 [params]

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "oslc"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"

    about_us = "<p>An open community building practical specifications for integrating data.</p>"
    copyright = "Copyright (c) 2017 OSLC; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/img/logo.png"

[Permalinks]
    news = "/news/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """This is a test site. For now, please refer to <a href="http://open-services.net">open-services.net</a>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    # not working
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to find out more?"
    subtitle = "OSLC is a community of software developers and organizations working to create a foundation for how software lifecycle tools share data"
    link_url = "/about/"
    link_text = "Find out more"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""
